package com.CrossingGuardJoe.viewer.images.defined;

public class ToolImages {
    public static final String[] ARROW_DOWN = {
            "$$$$$$$$$$$$$$$$",
            "$$GGGGGGGGGGGG$$",
            " $GGGGGGGGGGGG$ ",
            " $$GGGGGGGGGG$$ ",
            "  $$GGGGGGGG$$  ",
            "   $GGGGGGGG$   ",
            "   $$GGGGGG$$   ",
            "    $GGGGGG$    ",
            "    $$GGGG$$    ",
            "     $GGGG$     ",
            "     $$GG$$     ",
            "      $GG$      ",
            "      $$$$      ",
            "       $$       ",
            "       $$       ",
    };

    public static final String[] ARROW_RIGHT = {
            "$$",
            "$$$$",
            "$GG$$",
            "$GGG$$$",
            "$GGGGG$$$",
            "$GGGGGGG$$$",
            "$GGGGGGGGG$$$",
            "$GGGGGGGGGGG$$$",
            "$GGGGGGGGGGG$$$",
            "$GGGGGGGGG$$$",
            "$GGGGGGG$$$",
            "$GGGGG$$$",
            "$GGG$$$",
            "$GG$$",
            "$$$$",
            "$$",

    };

    public static final String[] KEY_UP = {
            "  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  ",
            "  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  ",
            "$$$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$$$",
            "$$$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$$$",
            "$$KK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KK$$",
            "$$KK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KK$$",
            "$$KKKK$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$KKKK$$",
            "$$KKKK$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKK$$$$KKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKK$$$$KKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKK$$$$$$KKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKK$$$$$$$$KKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKK$$$$$$$$KKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKK$$$$$$$$$$KKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKK$$$$$$$$$$KKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKK$$$$$$$$$$$$KKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKK$$$$$$$$$$$$KKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKK$$$$$$$$$$$$$$KKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$$$$$$$$$$$$KKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$$$$$$$$$$$$KKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKK$$$$$$$$$$$$$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKK$$$$$$$$$$$$$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKK$$$$$$$$$$$$$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$KKKK$$",
            "$$KKKK$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$KKKK$$",
            "$$KK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KK$$",
            "$$KK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KK$$",
            "$$$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$$$",
            "$$$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$$$",
            "  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  ",
            "  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  ",
    };

    public static final String[] KEY_DOWN = {
            "  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  ",
            "  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  ",
            "$$$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$$$",
            "$$$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$$$",
            "$$KK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KK$$",
            "$$KK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KK$$",
            "$$KKKK$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$KKKK$$",
            "$$KKKK$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKK$$$$$$$$$$$$$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKK$$$$$$$$$$$$$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKK$$$$$$$$$$$$$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$$$$$$$$$$$$KKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$$$$$$$$$$$$KKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKK$$$$$$$$$$$$$$KKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKK$$$$$$$$$$$$KKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKK$$$$$$$$$$$$KKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKK$$$$$$$$$$KKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKK$$$$$$$$$$KKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKK$$$$$$$$KKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKK$$$$$$$$KKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKK$$$$$$KKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKK$$$$KKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKK$$$$KKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$KKKK$$",
            "$$KKKK$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$KKKK$$",
            "$$KK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KK$$",
            "$$KK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KK$$",
            "$$$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$$$",
            "$$$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$$$",
            "  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  ",
            "  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  ",
    };

    public static final String[] KEY_RIGHT = {
            "  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  ",
            "  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  ",
            "$$$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$$$",
            "$$$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$$$",
            "$$KK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KK$$",
            "$$KK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KK$$",
            "$$KKKK$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$KKKK$$",
            "$$KKKK$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$KKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$KKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$$KKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$$$$KKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$$$$$$KKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$$$$$$$$KKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$$$$$$$$$$KKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$$$$$$$$$$$KKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$$$$$$$$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$$$$$$$$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$$$$$$$$$$$KKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$$$$$$$$$$KKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$$$$$$$$KKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$$$$$$KKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$$$$KKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$$KKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$KKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$KKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$KKKK$$",
            "$$KKKK$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$KKKK$$",
            "$$KK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KK$$",
            "$$KK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KK$$",
            "$$$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$$$",
            "$$$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$$$",
            "  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  ",
            "  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  ",
    };

    public static final String[] KEY_LEFT = {
            "  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  ",
            "  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  ",
            "$$$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$$$",
            "$$$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$$$",
            "$$KK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KK$$",
            "$$KK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KK$$",
            "$$KKKK$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$KKKK$$",
            "$$KKKK$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKK$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKK$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKK$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKK$$$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKK$$$$$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKK$$$$$$$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKK$$$$$$$$$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKK$$$$$$$$$$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$$$$$$$$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKK$$$$$$$$$$$$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKK$$$$$$$$$$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKK$$$$$$$$$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKK$$$$$$$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKK$$$$$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKK$$$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKK$$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKK$$$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKK$$$KKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KKKK$$",
            "$$KKKK$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$KKKK$$",
            "$$KKKK$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$KKKK$$",
            "$$KK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KK$$",
            "$$KK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$KK$$",
            "$$$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$$$",
            "$$$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$$$",
            "  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  ",
            "  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  ",
    };

    public static final String[] KEY_ESC = {
        "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
        "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
        "$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$",
        "$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$",
        "$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$",
        "$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$",
        "$$KKKK$$$$$$$$KKKKKKKKKKKKKKKKKKKKKKK$$",
        "$$KKKK$$$$$$$$KKKKKKKKKKKKKKKKKKKKKKK$$",
        "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$",
        "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$",
        "$$KKKK$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$",
        "$$KKKK$$KKKKKKKK$$$$$$$KK$$$$$$$$KKKK$$",
        "$$KKKK$$KKKKKKKK$$$$$$$KK$$$$$$$$KKKK$$",
        "$$KKKK$$$$$$$KKK$$KKKKKKK$$KKKKKKKKKK$$",
        "$$KKKK$$$$$$$KKK$$KKKKKKK$$KKKKKKKKKK$$",
        "$$KKKK$$KKKKKKKK$$KKKKKKK$$KKKKKKKKKK$$",
        "$$KKKK$$KKKKKKKK$$$$$$$KK$$KKKKKKKKKK$$",
        "$$KKKK$$KKKKKKKK$$$$$$$KK$$KKKKKKKKKK$$",
        "$$KKKK$$KKKKKKKKKKKKK$$KK$$KKKKKKKKKK$$",
        "$$KKKK$$KKKKKKKKKKKKK$$KK$$KKKKKKKKKK$$",
        "$$KKKK$$KKKKKKKKKKKKK$$KK$$KKKKKKKKKK$$",
        "$$KKKK$$$$$$$$KK$$$$$$$KK$$$$$$$$KKKK$$",
        "$$KKKK$$$$$$$$KK$$$$$$$KK$$$$$$$$KKKK$$",
        "$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$",
        "$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$",
        "$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$",
        "$$KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK$$",
        "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
        "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    };
}
