package com.CrossingGuardJoe.viewer.images;

public class RoadElementsImages {
    public static final String[] SIGNAL = {
            "                 $$$$$                 ",
            "                $$qqq$$                ",
            "               $$qqqqq$$               ",
            "              $$qqqqqqq$$              ",
            "             $$qqqqqqqqq$$             ",
            "            $$qqqqqqqqqqq$$            ",
            "           $$qqqqqqqqqqqqq$$           ",
            "          $$qqqqqqqqqqqqqqq$$          ",
            "         $$qqqqq$$$$qqqqqqqq$$         ",
            "        $$qqqqqq$$$$qqqqqqqqq$$        ",
            "       $$qqqqqqq$$$$qqqqqqqqqq$$       ",
            "      $$qqqqqqqq$$$$qqqqqqqqqqq$$      ",
            "     $$qqqqqqqqqqq$$$$$qqqqqqqqq$$     ",
            "    $$qqqqqqqqqqqq$$$$$qqqqqqqqqq$$    ",
            "   $$qqqqqqqqqqqqq$$$qq$$qqqqqqqqq$$   ",
            "  $$qqqqqqqqqq$$$$$$$qq$$qqqqqqqqqq$$  ",
            " $$qqqqqqqqqqq$$$$$$$qq$$qqqqqqqqqqq$$ ",
            "$$qqqqqqqqqqqqqqqq$$$qqqqqqqqqqqqqqqq$$",
            "$qqqqqqqqqqqqqqqqq$$$qqqqqqqqqqqqqqqqq$",
            "$qqqqqqqqqqqqqqqqq$$$qqqqqqqqqqqqqqqqq$",
            "$$qqqqqqqqqqqqqqqq$$$qqqqqqqqqqqqqqqq$$",
            " $$qqqqqqqqqqqqq$$qq$$qqqqqqqqqqqqqq$$ ",
            "  $$qqqqqqqqqqqq$$qq$$qqqqqqqqqqqqq$$  ",
            "   $$qqqqqqqqq$$qqqqqq$qqqqqqqqqqq$$   ",
            "    $$qqqqqqqq$$qqqqqqq$$qqqqqqqq$$    ",
            "     $$qqqqqqq$$qqqqqqq$$qqqqqqq$$     ",
            "      $$qqqqq$$$qqqqq$$$$qqqqqq$$      ",
            "       $$qqqq$$$qqqqq$$$$qqqqq$$       ",
            "        $$qqqqqqqqqqqqqqqqqqq$$        ",
            "         $$qqqqqqqqqqqqqqqqq$$         ",
            "          $$qqqqqqqqqqqqqqq$$          ",
            "           $$qqqqqqqqqqqqq$$           ",
            "            $$qqqqqqqqqqq$$            ",
            "             $$qqqqqqqqq$$             ",
            "              $$qqqqqqq$$              ",
            "               $$qqqqq$$               ",
            "                $$$$$$$                ",
            "                $$$$$$$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "         $$$$$$$$$$$$$$$$$$$$$         ",
            "         $»»»»»»»»»»»»»»»»»»»$         ",
            "         $»»»»»»»»»»»»»»»»»»»$         ",
            "         $»»»»»»»»»»»»»»»»»»»$         ",
            "         $»»»»»»»»»»»»»»»»»»»$         ",
            "         $»»»»»»»»»»»»»»»»»»»$         ",
            "         $»»»»»»»»»»»»»»»»»»»$         ",
            "         $»»»»»»»»»»»»»»»»»»»$         ",
            "         $»»»»»»»»»»»»»»»»»»»$         ",
            "         $»»»»»»»»»»»»»»»»»»»$         ",
            "         $»»»»»»»»»»»»»»»»»»»$         ",
            "         $»»»»»»»»»»»»»»»»»»»$         ",
            "         $»»»»»»»»»»»»»»»»»»»$         ",
            "         $$$$$$$$$$$$$$$$$$$$$         ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $AAAAA$                ",
            "                $$$$$$$                ",
            "                 $$$$$                 ",


    };
}
