package com.CrossingGuardJoe.ViewerTest.menu;

import com.CrossingGuardJoe.gui.GUI;
import com.CrossingGuardJoe.model.Position;
import com.CrossingGuardJoe.model.menu.Menu;
import com.CrossingGuardJoe.model.menu.Option;
import com.CrossingGuardJoe.viewer.menu.MenuViewer;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.mockito.Mockito.*;

public class MenuViewerTest {
    Menu menuMock;
    GUI guiMock;
    Position positionMock;
    MenuViewer menuViewer;

    String[] LOGOGAME_IMAGE = {
            "             $$$$$$$$$$$$$$$$$$$$$$$$$$                   $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                                     $$$$$$$$$$$                                                                                                                                                                                                                                                                                                                            ",
            "            $$$$$$$$$$$$$$$$$$$$$$$$$$$$                  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                                 $$$$$RRRRRRR$$$$$                                $$$$$$$$$$$$$$$$$$$$$$$$$$$$                              $$$$$$$$$$$$$$$$$$$$$$$$$$$$                             $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$             $$$$$$$$$$$$$$$                 $$$$$$$$$$$$$$                         $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$        ",
            "            $$WWWWWWWWWWWWWWWWWWWWWWWW$$$                 $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$                              $$$$RRRRRRRRRRRR$$$$$$                             $$WWWWWWWWWWWWWWWWWWWWWWWW$$$                             $$WWWWWWWWWWWWWWWWWWWWWWWW$$$                            $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$            $$WWWWWWWWWWW$$$                $WWWWWWWWWWWW$$                        $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$       ",
            "            $$WWWWWWWWWWWWWWWWWWWWWWWW$$$$                $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$                           $$$RRRRRRRRRRRRRRRRRR$$$$$$                          $$WWWWWWWWWWWWWWWWWWWWWWWW$$$$                            $$WWWWWWWWWWWWWWWWWWWWWWWW$$$$                           $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$           $$WWWWWWWWWWW$$$$               $WWWWWWWWWWWW$$$                       $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$      ",
            "            $$WWWWWWWWWWWWWWWWWWWWWWWW$$$$$               $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$                        $$$RRRRRRRRRRRRRRRRRRRRRR$$$$$$                        $$WWWWWWWWWWWWWWWWWWWWWWWW$$$$$                           $$WWWWWWWWWWWWWWWWWWWWWWWW$$$$$                          $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$          $$WWWWWWWWWWW$$$$$              $WWWWWWWWWWWW$$$$                      $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$     ",
            "            $$WWWWWWWWWWWWWWWWWWWWWWWW$$$$$$              $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$                      $$RRRRRRRRRRRRRRRRRRRRRRRRR$$$$$$$                      $$WWWWWWWWWWWWWWWWWWWWWWWW$$$$$$                          $$WWWWWWWWWWWWWWWWWWWWWWWW$$$$$$                         $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$         $$WWWWWWWWWWW$$$$$$             $WWWWWWWWWWWW$$$$$                     $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$    ",
            "            $$WWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$            $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$                   $$RRRRRRRRRRRRRRRRRRRRRRRRRRR$$$$$$$$                    $$WWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$                         $$WWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$                        $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$        $$WWWWWWWWWWW$$$$$$$            $WWWWWWWWWWWW$$$$$$                    $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$   ",
            "      $$$$$$$$WWWWWW$$$$$$$$$$$$$WWWWW$$$$$$$$$           $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWW$$$$$$$$$                 $$RRRRRRRRRRRRRRRRRRRRRRRRRRRRR$$$$$$$$             $$$$$$$$WWWWW$$$$$$$$$$$$$$WWWWW$$$$$$$$                  $$$$$$$$WWWWW$$$$$$$$$$$$$$WWWWW$$$$$$$$                       $$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$       $$WWWWWWWWWWW$$$$$$$$$          $WWWWWWWWWWWW$$$$$$$             $$$$$$$WWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  ",
            "      $WWWWWWWWWWWWW$$$$$$$$$$$$$WWWWWWWWWWWW$$$          $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$               $$RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR$$$$$$$$$           $$WWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWW$$                 $$WWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWW$$                      $$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$      $$WWWWWWWWWWWWWWWWWW$$$         $WWWWWWWWWWWW$$$$$$$$            $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ ",
            "      $WWWWWWWWWWWWW$$$$$$$$$$$$$WWWWWWWWWWWW$$$$         $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$             $$RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR$$$$$$$$           $$WWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWW$$$                $$WWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWW$$$                      $$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$     $$WWWWWWWWWWWWWWWWWW$$$$        $WWWWWWWWWWWW$$$$$$$$$           $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "      $WWWWWWWWWWWWW$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$        $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$           $$RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR$$$$$$$$          $$WWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$               $$WWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$                      $$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$     $$WWWWWWWWWWWWWWWWWW$$$$$       $WWWWWWWWWWWW$$$$$$$$$$          $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "      $WWWWWWWWWWWWW$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$       $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$          $RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR$$$$$$$$         $$WWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$              $$WWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$                      $$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$     $$WWWWWWWWWWWWWWWWWW$$$$$$      $WWWWWWWWWWWW$$$$$$$$$$          $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "$$$$$$$WWWWWWWWWWWWW$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$      $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$        $$RRRRRRRRRRRRRRRRRRRRRRRR$$RRRRRRRRRRR$$$$$$$$$        $$WWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$             $$WWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$                      $$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$     $$WWWWWWWWWWWWWWWWWW$$$$$$$     $WWWWWWWWWWWW$$$$$$$$$$          $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "$$$$$$$WWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$     $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$       $RRRRRRRRRRRRRRRRRRRRRRRR$$$$RRRRRRRRRRR$$$$$$$$$       $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$            $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                      $$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$     $$WWWWWWWWWWWWWWWWWW$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$   $$$$$$$$WWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "$$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$     $$RRRRRRRRRRRRRRRRRRRRRRR$$WW$$RRRRRRRRRR$$$$$$$$$$      $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$           $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                      $$$$$$$$WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$     $$WWWWWWWWWWWWWWWWWWWWWWWW$$$   $WWWWWWWWWWWW$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "$$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$    $RRRRRRRRRRRRRRRRRRRRRRR$$WWWW$$RRRRRRRRRR$$$$$$$$$@     $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$          $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                      $$$$$$$WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$     $$WWWWWWWWWWWWWWWWWWWWWWWW$$$$  $WWWWWWWWWWWW$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "$$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $$RRRRRRRRRRRRRRRRRRRRRR$$WWWWWW$$RRRRRRRRR$$$$$$$$$$     $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$         $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                      $$$$$$WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$     $$WWWWWWWWWWWWWWWWWWWWWWWW$$$$  $WWWWWWWWWWWW$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "$$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $RRRRRRRRRRRRRRRRRRRRRR$$WWWWWWWW$$RRRRRRRRR$$$$$$$$$     $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$         $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                       $$$$$WWWWWWWWWWWW$$$$$$$$$$                 $$WWWWWWWWWWWWWWWWWWWWWWWW$$$$$ $WWWWWWWWWWWW$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$                         ",
            "$$WWWWWWWWWWW$$$$$$$$$$$$$$$$$       $$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$        $WWWWWWWWWWWW$$$$$$$$$$   $RRRRRRRRRRRRRRRRRRRRR$$WWWWWWWWW$$RRRRRRRRR$$$$$$$$$$    $$WWWWWWWWWWW$$$$$$$$$$$      $$$$$$$$$$$$$$$$$$$         $$WWWWWWWWWWW$$$$$$$$$$$      $$$$$$$$$$$$$$$$$$$                          $$WWWWWWWWWWWW$$$$$$$$$$                 $$WWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$                         ",
            "$$WWWWWWWWWWW$$$$$$$$$$$$$$$$$        $$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$  $$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $RRRRRRRRRRRRRRRRRRRR$$WWWWWWWWW$$RRRRRRRRRR$$$$$$$$$$    $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$         $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                          $$WWWWWWWWWWWW$$$$$$$$$$                 $$WWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$                         ",
            "$$WWWWWWWWWWW$$$$$$$$$$$$$$$$$         $$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$ $$$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $RRRRRRRRRRRRRRRRRRR$$WWWWWWWWW$$RRRRRRRRRRRR$$$$$$$$$$   $$$$$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$         $$$$$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$                          $$WWWWWWWWWWWW$$$$$$$$$$                 $$WWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$        ",
            "$$WWWWWWWWWWW$$$$$$$$$$$$$$$$$          $$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$ $$WWWWWWWWWWWWWWWWWW$$$$$$$$$$  $$RRRRRRRRRRRRRRRRRR$$WWWWWWWWW$$RRRRRRRRRRRRR$$$$$$$$$$    $$$$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$          $$$$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$                          $$WWWWWWWWWWWW$$$$$$$$$$                 $$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWWWWWWWW$$$       ",
            "$$WWWWWWWWWWW$$$$$$$$$$$$$$$$$           $$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$ $$WWWWWWWWWWWWWWWWWW$$$$$$$$$$  $RRRRRRRRRRRRRRRRRR$$WWWWWWWWW$$RRRRRRRRRRRRRR$$$$$$$$$$     $$$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$           $$$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$                          $$WWWWWWWWWWWW$$$$$$$$$$                 $$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWWWWWWWW$$$$      ",
            "$$WWWWWWWWWWW$$$$$$$$$$$                                  $WWWWWWWWWWWW$$$$$$$$$$$ $$WWWWWWWWWWWWWWWWWW$$$$$$$$$$  $RRRRRRRRRRRRRRRRR$$WWWWWWWWW$$RRRRRRRRRRRRRRR$$$$$$$$$$$     $$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$             $$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$                          $$WWWWWWWWWWWW$$$$$$$$$$                 $$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$  $WWWWWWWWWWWWWWWWWW$$$$$     ",
            "$$WWWWWWWWWWW$$$$$$$$$$$                                  $WWWWWWWWWWWW$$$$$$$$$$$ $$WWWWWWWWWWWWWWWWWW$$$$$$$$$$  $RRRRRRRRRRRRRRRR$$WWWWWWWWW$$RRRRRRRRRRRRRRRR$$$$$$$$$$$      $$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$                 $$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$                              $$WWWWWWWWWWWW$$$$$$$$$$                 $$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$  $WWWWWWWWWWWWWWWWWW$$$$$$    ",
            "$$WWWWWWWWWWW$$$$$$$$$$$                                  $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWWWWWWWW$$$$$$$$$$  $RRRRRRRRRRRRRRR$$WWWWWWWWW$$RRRRRRRRRRRRRRRRR$$$$$$$$$$$       $$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$                 $$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$                             $$WWWWWWWWWWWW$$$$$$$$$$                 $$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$  $WWWWWWWWWWWWWWWWWW$$$$$$$   ",
            "$$WWWWWWWWWWW$$$$$$$$$$$                                  $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWW$$$$$$$$$$$$$$$$$$$$$$$  $$RRRRRRRRRRRRR$$WWWWWWWWW$$RRRRRRRRRRRRRRRRRR$$$$$$$$$$$        $$$$$$$$$$$$$$$$$$$$$$$$$$$WWWWWW$$$$$$$$                 $$$$$$$$$$$$$$$$$$$$$$$$$$$WWWWWW$$$$$$$$                            $$WWWWWWWWWWWW$$$$$$$$$$                 $$WWWWWWWWWWWW$$$$$$$WWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$  $$$$$$$WWWWWWWWWWWW$$$$$$$$  ",
            "$$WWWWWWWWWWW$$$$$$$$$$$                                  $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$   $RRRRRRRRRRRR$$WWWWWWWWW$$RRRRRRRRRRRRRRRRRR$$$$$$$$$$$$         $$$$$$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$                 $$$$$$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$                           $$WWWWWWWWWWWW$$$$$$$$$$                 $$WWWWWWWWWWWW$$$$$$$WWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$  $$$$$$$$WWWWWWWWWWW$$$$$$$$$ ",
            "$$WWWWWWWWWWW$$$$$$$$$$$                                  $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$   $RRRRRRRRRRR$$WWWWWWWWW$$RRRRRRRRRRRRRRRRRRR$$$$$$$$$$$$          $$$$$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$                 $$$$$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$                          $$WWWWWWWWWWWW$$$$$$$$$$                 $$WWWWWWWWWWWW$$$$$$$WWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$   $$$$$$$WWWWWWWWWWW$$$$$$$$$$",
            "$$WWWWWWWWWWW$$$$$$$$$$$                                  $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$   $RRRRRRRRRR$$WWWWWWWWW$$RRRRRRRRRRRRRRRRRRRR$$$$$$$$$$$$           $$$$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$                  $$$$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$                          $$WWWWWWWWWWWW$$$$$$$$$$                 $$WWWWWWWWWWWW$$$$$$$WWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$    $$$$$$WWWWWWWWWWW$$$$$$$$$$",
            "$$WWWWWWWWWWW$$$$$$$$$$$                                  $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$   $$RRRRRRRR$$WWWWWWWWW$$RRRRRRRRRRRRRRRRRRRRR$$$$$$$$$$$$             $$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$                   $$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$                         $$WWWWWWWWWWWW$$$$$$$$$$                 $$WWWWWWWWWWWW$$$$$$$WWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$     $$$$$WWWWWWWWWWW$$$$$$$$$$",
            "$$WWWWWWWWWWW$$$$$$$$$$$                                  $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$    $RRRRRRRR$$WWWWWWWW$$RRRRRRRRRRRRRRRRRRRRR$$$$$$$$$$$$$              $$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$                   $$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$                        $$WWWWWWWWWWWW$$$$$$$$$$                 $$WWWWWWWWWWWW$$$$$$$WWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$      $$$$WWWWWWWWWWW$$$$$$$$$$",
            "$$$$$$$$WWWWW$$$$$$$$$$$        $$$$$$$$$$$$$$            $WWWWWWWWWWWW$$$$$$$WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$    $$RRRRRRRR$$WWWWWW$$RRRRRRRRRRRRRRRRRRRRRR$$$$$$$$$$$$   $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$      $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$                       $$WWWWWWWWWWWW$$$$$$$$$$                 $$WWWWWWWWWWWW$$$$$$$$$$$$$WWWWWWWWWWWWWWWWWW$$$$$$$$$$   $$$$$$$$WWWWW$$$$$$$$$$$       $$$WWWWWWWWWWW$$$$$$$$$$",
            "$$$$$$$$WWWWW$$$$$$$$$$$       $$$$$$$$$$$$$$$$           $WWWWWWWWWWWW$$$$$$$$WWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$     $RRRRRRRRR$$WWWW$$RRRRRRRRRRRRRRRRRRRRRRR$$$$$$$$$$$$   $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$     $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$                      $$WWWWWWWWWWWW$$$$$$$$$$                 $$WWWWWWWWWWWW$$$$$$$$$$$$$WWWWWWWWWWWWWWWWWW$$$$$$$$$$    $$$$$$$WWWWWWWWWWWW$$$$        $$WWWWWWWWWWW$$$$$$$$$$",
            " $$$$$$$WWWWWWWWWWW$$$$$       $$WWWWWWWWWWWW$$$          $WWWWWWWWWWWW$$$$$$$$WWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$     $$RRRRRRRRR$$WW$$RRRRRRRRRRRRRRRRRRRRRRR$$$$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$    $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$                     $$WWWWWWWWWWWW$$$$$$$$$$                 $$WWWWWWWWWWWW$$$$$$$$$$$$$WWWWWWWWWWWWWWWWWW$$$$$$$$$$     $$$$$$WWWWWWWWWWWW$$$$        $$WWWWWWWWWWW$$$$$$$$$$",
            "  $$$$$$WWWWWWWWWWW$$$$$       $$WWWWWWWWWWWW$$$$         $WWWWWWWWWWWW$$$$$$$$WWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$     @$RRRRRRRRRR$$$$RRRRRRRRRRRRRRRRRRRRRRR$$$$$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$                    $$WWWWWWWWWWWW$$$$$$$$$$                 $$WWWWWWWWWWWW$$$$$$$$$$$$$WWWWWWWWWWWWWWWWWW$$$$$$$$$$      $$$$$WWWWWWWWWWWW$$$$        $$WWWWWWWWWWW$$$$$$$$$$",
            "   $$$$$WWWWWWWWWWW$$$$$$      $$WWWWWWWWWWWW$$$$$        $WWWWWWWWWWWW$$$$$$$$WWWWWWWWWWWWWWWWW$$$$$$                 $$RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR$$$$$$$$$$$$$    $$WWWWWWWWWWW$$$$$              $WWWWWWWWWWWW$$$$$$$$$$   $$WWWWWWWWWWW$$$$$              $WWWWWWWWWWWW$$$$$$$$$$                    $$WWWWWWWWWWWW$$$$$$$$$$                 $$WWWWWWWWWWWW$$$$$$$$$$$$$WWWWWWWWWWWWWWWWWW$$$$$$$$$$       $$$$WWWWWWWWWWWW$$$$$       $$WWWWWWWWWWW$$$$$$$$$$",
            "    $$$$WWWWWWWWWWW$$$$$$$     $$WWWWWWWWWWWW$$$$$$       $WWWWWWWWWWWW$$$$$$$$WWWWWWWWWWWWWWWWW$$$$$$$                 $$RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR$$$$$$$$$$$$$     $$WWWWWWWWWWW$$$$$$             $WWWWWWWWWWWW$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$             $WWWWWWWWWWWW$$$$$$$$$$                    $$WWWWWWWWWWWW$$$$$$$$$$                 $$WWWWWWWWWWWW$$$$$$$$$$$$$WWWWWWWWWWWWWWWWWW$$$$$$$$$$        $$$WWWWWWWWWWWW$$$$$$      $$WWWWWWWWWWW$$$$$$$$$$",
            "     $$$WWWWWWWWWWW$$$$$$$$$$$$$$WWWWWW$$$$$$$$$$$$$      $WWWWWWWWWWWW$$$$$$$$WWWWWWWWWWWWWWWWW$$$$$$$$                 $$RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR$$$$$$$$$$$$$$     $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWW$$$$$$$$$$$$$$$$   $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWW$$$$$$$$$$$$$$$$       �$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$$$$�             $$WWWWWWWWWWWW$$$$$$$$$$$$$WWWWWWWWWWWWWWWWWW$$$$$$$$$$         $$WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWW$$$$$$$$$$",
            "      $$$$$$$$WWWWWW$$$$$$$$$$$$$WWWWWW$$$$$$$$$$$$$$     $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$                 $$RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR$$$$$$$$$$$$$      $$$$$$$$WWWWW$$$$$$$$$$$$$$$$$$$$WWWWWW$$$$$$$$$$$$$$$$   $$$$$$$$WWWWW$$$$$$$$$$$$$$$$$$$$WWWWWW$$$$$$$$$$$$$$$$       �$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$$$$$�            $$WWWWWWWWWWWW$$$$$$$$$$  $$$$$$$$WWWWWWWWWWW$$$$$$$$$$          $$$$$$$$WWWWW$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$",
            "       $$$$$$$WWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWWWWWWWW$$$                 $$RRRRRRRRRRRRRRRRRRRRRRRRRRRRR$$$$$$$$$$$$$$       $$$$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$    $$$$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$       �$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$�           $$WWWWWWWWWWWW$$$$$$$$$$   $$$$$$$WWWWWWWWWWW$$$$$$$$$$           $$$$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$",
            "        $$$$$$WWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWWWWWWWW$$$$                 $$RRRRRRRRRRRRRRRRRRRRRRRRRRR$$$$$$$$$$$$$$         $$$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$     $$$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$       �$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$�          $$WWWWWWWWWWWW$$$$$$$$$$    $$$$$$WWWWWWWWWWW$$$$$$$$$$            $$$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$",
            "         $$$$$WWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWWWWWWWW$$$$$                 $$$RRRRRRRRRRRRRRRRRRRRRRRR$$$$$$$$$$$$$$           $$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$      $$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$       �$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$�         $$WWWWWWWWWWWW$$$$$$$$$$     $$$$$WWWWWWWWWWW$$$$$$$$$$             $$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$",
            "          $$$$WWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWWWWWWWW$$$$$$                 @$$RRRRRRRRRRRRRRRRRRRRR$$$$$$$$$$$$$$$             $$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$       $$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$       �$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$�        $$WWWWWWWWWWWW$$$$$$$$$$      $$$$WWWWWWWWWWW$$$$$$$$$$              $$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$",
            "           $$$WWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWWWWWWWW$$$$$$$                  $$$$RRRRRRRRRRRRRRRR$$$$$$$$$$$$$$$$               $$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$        $$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$       �$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$�       $$WWWWWWWWWWWW$$$$$$$$$$       $$$WWWWWWWWWWW$$$$$$$$$$               $$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$",
            "            $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$   $$$$$$$$$$$$$$$$$$$$$$$$ $$$$$$$$$$$$$$$$$$$$$$$$$$$$                    $$$RRRRRRRRRRRR$$$$$$$$$$$$$$$$$                 $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$         $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$        $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$�      $$$$$$$$$$$$$$$$$$$$$$$$        $$$$$$$$$$$$$$$$$$$$$$$                $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "             $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$    $$$$$$$$$$$$$$$$$$$$$$$  $$$$$$$$$$$$$$$$$$$$$$$$$$$$                     $$$$RRRR$$$$$$$$$$$$$$$$$$$$$                   $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$          $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$        �$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$�      $$$$$$$$$$$$$$$$$$$$$$$         $$$$$$$$$$$$$$$$$$$$$$                 $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "              $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$     $$$$$$$$$$$$$$$$$$$$$$   $$$$$$$$$$$$$$$$$$$$$$$$$$$$                       $$$$$$$$$$$$$$$$$$$$$$$$$                     $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$           $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$         �$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$       $$$$$$$$$$$$$$$$$$$$$$          $$$$$$$$$$$$$$$$$$$$$   $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "            $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$   $$$$$$$$$$$$$$$$$$$$$$$$    $$$$$$$$$$$$$$$$$$$$$$$$$$$               $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$   $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$          �$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$        $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$",
            "            $$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$         $WWWWWWWWWWWW$$$$$$$$$$$     $$$$WWWWWWWWWWWW$$$$$$$$$$               $$WWWWWWWWWWWWWWWWWW$$$$$$$$                  $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$         $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$                 �$$$$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWW$$$$$$$$$         $$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$",
            "            $$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$         $WWWWWWWWWWWW$$$$$$$$$$$      $$$WWWWWWWWWWWW$$$$$$$$$$               $$WWWWWWWWWWWWWWWWWW$$$$                      $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$         $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$                  �$$$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWW$$$$$$$$$          $$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$",
            "            $$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$         $WWWWWWWWWWWW$$$$$$$$$$$       $$WWWWWWWWWWWW$$$$$$$$$$               $$WWWWWWWWWWWWWWWWWW$$$$                      $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$         $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$                   �$$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWW$$$$$$$$$           $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$",
            "            $$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$        $WWWWWWWWWWWW$$$$$$$$$$$       $$WWWWWWWWWWWW$$$$$$$$$$               $$WWWWWWWWWWWWWWWWWW$$$$$                     $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$         $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$                    �$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWW$$$$$$$$$           $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$",
            "            $$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$       $WWWWWWWWWWWW$$$$$$$$$$$       $$WWWWWWWWWWWW$$$$$$$$$$               $$WWWWWWWWWWWWWWWWWW$$$$$$                    $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$         $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$                     �$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWW$$$$$$$$$           $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "      $$$$$$$$WWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$      $WWWWWWWWWWWW$$$$$$$$$$$       $$WWWWWWWWWWWW$$$$$$$$$$         $$$$$$$$WWWWW$$$$$$$$WWWWW$$$$$$$$                  $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWW$$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWW$$$$$$$$$$$$$$$$$                      �$$$$$$$$$$$$$$$$$$$WWWWWWWWWWW$$$$$$$$$     $$$$$$$WWWWW$$$$$$$$$$$$$$$$$$$$WWWWWW$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "      $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$     $WWWWWWWWWWWW$$$$$$$$$         $$WWWWWWWWWWWW$$$$$$$$$          $WWWWWWWWWWWW$$$$$$$$WWWWWWWWWWW$$$                 $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$           $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWW$$$                                                $$WWWWWWWWWWW$$$$$$$$$     $WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWW$$$           $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "      $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$WWWWWWWWWWW$$$$                $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$          $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWW$$$$                                               $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWW$$$$          $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "      $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$WWWWWWWWWWW$$$$$               $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$         $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWW$$$$$                                              $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWW$$$$$         $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "      $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$WWWWWWWWWWW$$$$$$              $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$        $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWW$$$$$$                                             $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWW$$$$$$        $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "$$$$$$$WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$WWWWWWWWWWW$$$$$$$             $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$       $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWW$$$$$$$|                                           $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWW$$$$$$$       $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "$$$$$$$WWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $$$$$$$WWWWWW$$$$$$$$$$$$$$$$$$$$WWWWW$$$$$$$$            $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$      $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWW$$$$$$$$|                                          $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWW$$$$$$$$      $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "$WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$           $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$     $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$|                                         $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWW$$$$$$$$$     $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "$WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$          $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$|                                        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "$WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$         $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$                                        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$                                ",
            "$WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$        $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$ $WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$                                       $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$                                ",
            "$WWWWWWWWWWWW$$$$$$$$$$$$$$$$$                            $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$ $$$WWWWWWWWWWWW$$$$$$       $WWWWWWWWWWWW$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$       $$$WWWWWWWWWWWW$$$$$$                                      $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$                                ",
            "$WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$             $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$  $$WWWWWWWWWWWW$$$$$$$      $WWWWWWWWWWWW$$$$$$$$$$   $$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$                                     $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$                      ",
            "$WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$            $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$     $WWWWWWWWWWWW$$$$$$$$$$   $$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$                                    $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$                     ",
            "$WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWWWWWWW$$$           $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$$                                   $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$                    ",
            "$WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWWWWWWW$$$$          $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$$$                                  $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$                   ",
            "$WWWWWWWWWWWW$$$$$$$$$$  $$WWWWWWWWWWWWWWWWW$$$$$         $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$$$                                  $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$                  ",
            "$WWWWWWWWWWWW$$$$$$$$$$  $$WWWWWWWWWWWWWWWWW$$$$$$        $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$$$                                  $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$                 ",
            "$WWWWWWWWWWWW$$$$$$$$$$  $$WWWWWWWWWWWWWWWWW$$$$$$$       $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$$$                                  $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$                ",
            "$WWWWWWWWWWWW$$$$$$$$$$  $$$$$$$$WWWWWWWWWWW$$$$$$$$      $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWW$$$$$$$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$$$                                  $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$               ",
            "$WWWWWWWWWWWW$$$$$$$$$$  $$$$$$$$WWWWWWWWWWW$$$$$$$$$     $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$$$                                  $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$              ",
            "$WWWWWWWWWWWW$$$$$$$$$$   $$$$$$$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$$$                                  $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$             ",
            "$WWWWWWWWWWWW$$$$$$$$$$    $$$$$$WWWWWWWWWWW$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$$$                                  $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$             ",
            "$WWWWWWWWWWWW$$$$$$$$$$     $$$$$WWWWWWWWWWW$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$$$                                  $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$             ",
            "$WWWWWWWWWWWW$$$$$$$$$$      $$$$WWWWWWWWWWW$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$$$                                  $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$             ",
            "$$$$$$$$WWWWW$$$$$$$$$$       $$$WWWWWWWWWWW$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$   $$$$$$$WWWWWW$$$$$$$$$$$$$$$$  �$$$$$$$$$$$$$                  $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$             ",
            "$$$$$$$$WWWWWWWWWWW$$$$        $$WWWWWWWWWWW$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$WWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$  $$$$$$$$$$$$$$$                 $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$             ",
            " $$$$$$$WWWWWWWWWWW$$$$        $$WWWWWWWWWWW$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$WWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$  $$WWWWWWWWWWW$$$                $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$             ",
            "  $$$$$$WWWWWWWWWWW$$$$$       $$WWWWWWWWWWW$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$WWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$  $$WWWWWWWWWWW$$$$               $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$             ",
            "   $$$$$WWWWWWWWWWW$$$$$$      $$WWWWWWWWWWW$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$WWWWWWWWWWWWWWWWW$$$$$$              $WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$  $$WWWWWWWWWWW$$$$$              $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$                                ",
            "    $$$$WWWWWWWWWWW$$$$$$$     $$WWWWWWWWWWW$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$        $$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$WWWWWWWWWWWWWWWWW$$$$$$$             $WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$  $$WWWWWWWWWWW$$$$$$             $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$        $$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$                                ",
            "     $$$WWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWW$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$WWWWWWWWWWWWWWWWW$$$$$$$$            $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWWW$$$$$$$$$$$$$$$$$$$$$$  $$WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWW$$$$$$$$$$    $WWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$WWWWW$$$$$$$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$         ",
            "      $$$$$$$$WWWWW$$$$$$$$$$$$$$WWWWWWWWWWW$$$$$$$$$$$   $$$$$$$$WWWWW$$$$$$$$$$$$$$$$$$$$WWWWW$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$           $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWW$$$$$$$$$$$$$$$$$$$$$$$  $$$$$$$$WWWWW$$$$$$$$$$$$$$$$$$$$WWWWWW$$$$$$$$$$$$$$$$    $$$$$$$WWWWWW$$$$$$$$$$$$$$$$$$$WWWWWW$$$$$$$$$$$$$$$$    $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$        ",
            "       $$$$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$   $$$$$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWWWWWWWW$$$          $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$   $$$$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$    $$$$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$    $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$       ",
            "        $$$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$    $$$$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWWWWWWWW$$$$         $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$$$$    $$$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$     $$$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$    $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$      ",
            "         $$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$     $$$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$$$$$$$WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWWWWWWWW$$$$$        $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$           $$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$      $$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$    $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$     ",
            "          $$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$      $$$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$$$$$WWWWWWWWWWWWWWWWWW$$$$$$       $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$            $$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$       $$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$    $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$    ",
            "           $$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$       $$$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$         $WWWWWWWWWWWW$$$$$$$$$$   $WWWWWWWWWWWW$$$$$$$$$$ $$$WWWWWWWWWWWWWWWWWW$$$$$$$      $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$$             $$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$        $$$WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$$$$$$$$$$    $WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW$$$$$$$   ",
            "            $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$        $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$   $$$$$$$$$$$$$$$$$$$$$$$         $$$$$$$$$$$$$$$$$$$$$$$   $$$$$$$$$$$$$$$$$$$$$$$  $$$$$$$$$$$$$$$$$$$$$$$$$$$$     $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$              $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$         $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$    $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  ",
            "             $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$         $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$    $$$$$$$$$$$$$$$$$$$$$$          $$$$$$$$$$$$$$$$$$$$$$    $$$$$$$$$$$$$$$$$$$$$$   $$$$$$$$$$$$$$$$$$$$$$$$$$$$     $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$               $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$          $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$     $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ ",
            "              $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$          $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$     $$$$$$$$$$$$$$$$$$$$$           $$$$$$$$$$$$$$$$$$$$$     $$$$$$$$$$$$$$$$$$$$$    $$$$$$$$$$$$$$$$$$$$$$$$$$$$     $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$           $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$      $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "               $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$           $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$      $$$$$$$$$$$$$$$$$$$$            $$$$$$$$$$$$$$$$$$$$      $$$$$$$$$$$$$$$$$$$$     $$$$$$$$$$$$$$$$$$$$$$$$$$$      $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                 $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$            $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$       $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "                $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$            $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$             $$$$$$$$$$$$$$$$$$$             $$$$$$$$$$$$$$$$$$$       $$$$$$$$$$$$$$$$$$$      $$$$$$$$$$$$$$$$$$$$$$$$$$       $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                        $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                    $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$              $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "                 $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$              $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$              $$$$$$$$$$$$$$$$$$              $$$$$$$$$$$$$$$$$$        $$$$$$$$$$$$$$$$$$       $$$$$$$$$$$$$$$$$$$$$$$$$        $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                         $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                     $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$               $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "                  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$               $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$               $$$$$$$$$$$$$$$$$               $$$$$$$$$$$$$$$$$         $$$$$$$$$$$$$$$$$        $$$$$$$$$$$$$$$$$$$$$$$$         $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                          $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                      $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "                   $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                $$$$$$$$$$$$$$$$                $$$$$$$$$$$$$$$$          $$$$$$$$$$$$$$$$         $$$$$$$$$$$$$$$$$$$$$$$          $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                           $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                       $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                 $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "                    $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                 $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                 $$$$$$$$$$$$$$$                 $$$$$$$$$$$$$$$           $$$$$$$$$$$$$$$          $$$$$$$$$$$$$$$$$$$$$$           $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                            $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                        $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
            "                     $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                  $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                  $$$$$$$$$$$$$$                  $$$$$$$$$$$$$$            $$$$$$$$$$$$$$           $$$$$$$$$$$$$$$$$$$$$            $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                             $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                         $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$                   $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$",
    };

    String[] ARROW_RIGHT = {
            "$$",
            "$$$$",
            "$GG$$",
            "$GGG$$$",
            "$GGGGG$$$",
            "$GGGGGGG$$$",
            "$GGGGGGGGG$$$",
            "$GGGGGGGGGGG$$$",
            "$GGGGGGGGGGG$$$",
            "$GGGGGGGGG$$$",
            "$GGGGGGG$$$",
            "$GGGGG$$$",
            "$GGG$$$",
            "$GG$$",
            "$$$$",
            "$$",

    };

    @BeforeEach
    void init() {
        menuMock = mock(Menu.class);
        guiMock = mock(GUI.class);
        positionMock = mock(Position.class);
        menuViewer = new MenuViewer(menuMock);
    }

    @Test
    void drawTitle() {
        when(positionMock.getX()).thenReturn(130);
        when(positionMock.getY()).thenReturn(50);

        Position expectedPosition = new Position(positionMock.getX(), positionMock.getY());
        menuViewer.drawTitle(guiMock);

        verify(guiMock).drawImage(expectedPosition, LOGOGAME_IMAGE);
    }

    @Test
    void drawElements() {
        Option option1 = new Option("Option 1", new Position(100, 200), null);
        Option option2 = new Option("Option 2", new Position(150, 250), null);
        when(menuMock.getNumberOptions()).thenReturn(2);
        when(menuMock.getOption(0)).thenReturn(option1);
        when(menuMock.getOption(1)).thenReturn(option2);
        when(menuMock.isSelectedOption(0)).thenReturn(true);
        when(menuMock.isSelectedOption(1)).thenReturn(false);

        Position expectedPosition1 = option1.position();
        Position expectedPosition2 = option2.position();

        menuViewer.drawElements(guiMock);

        verify(guiMock).drawText(expectedPosition1, "Option 1", "#FFFFFF");
        verify(guiMock).drawText(expectedPosition2, "Option 2", "#FFFFFF");
        verify(guiMock).drawImage(new Position(expectedPosition1.getX() - 15, expectedPosition1.getY()), ARROW_RIGHT);
    }

    @Test
    void drawInformation() {
        menuViewer.drawInformation(guiMock);

        verifyNoInteractions(guiMock);
    }

}